version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=0b53f9d78f8c.ngrok-free.app
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://0b53f9d78f8c.ngrok-free.app/
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
    volumes:
      - ./n8n_data:/home/node/.n8n
